# -------------------------------
# Site settings
# -------------------------------
title: Greg Mauz
email: jtarr.rams@gmail.com
description: "A portfolio and resume for my work as a radio talent"
baseurl: ""
url: "http://yourdomain.com"